mysql:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=wisemoney42
  volumes:
    - "data/mysql:/var/lib/mysql"

application:
  build: .
  volumes:
    - "app:/src/app"
  ports:
    - 80:3000
  links:
    - mysql